### ISSUE TITLE
--mode SEMANTIC option is working ?

### ISSUE THREAD

**Issue by 39ff** [RameshAditya/scoper#3]
Hi.
I tried the SEMANTIC option, but it seems to be hanging.
Is this project still being maintained?
Thanks.

**Comment by RameshAditya** [comment]
Hi,
The semantic matching relies on training a model and then applying some heuristics to identify similar captions. This can be a resource-intensive process and is dependent on the user's processing abilities as well.

I suspect [this part of the code](https://github.com/RameshAditya/scoper/blob/master/scoper.py#L88) is what's taking time to process - confirming this locally should be easy too by placing timers on your local fork of the script.

That said, currently this project is not actively being maintained and there are no current plans on optimizing the semantic matching algorithm.

If my suspicion proves correct though and if you strongly require an optimization for this, then [this stackoverflow answer](https://stackoverflow.com/a/43067907) seems like a promising solution to explore.

**Comment by 39ff** [comment]
OK Thanks.
